spring:
  cloud:
    nacos:
      config:
        server-addr: 198.19.249.35:7847
        namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
        group: MS_GROUP
      discovery:
        server-addr: 198.19.249.35:7847
        namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
        group: MS_GROUP
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
