# 服务相关配置
server:
  port: 10002
  servlet:
    context-path: /doc-service

spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher # SpringBoot2.6.X版本兼容knife4J3.0配置

  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/document_service
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Hikari数据库连接池
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10 # 最大连接数
      connection-timeout: 30000 # 连接超时（毫秒）
      idle-timeout: 60000 # 空闲的连接的生命时长（毫秒）
      max-lifetime: 60000 # 连接的生命时长（毫秒）
      validation-timeout: 3000 # 验证连接有效性（毫秒）

