spring:
  application:
    name: zuulservice
  profiles:
    active: default

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true                      # 用来指明使用IP而不是自身服务名称来注册自身服务
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true                   # 用于指定该客户端实例是否在Eureka服务器上注册自己的信息以提供其他服务进行发现
    fetchRegistry: true                        # 用于指定该客户端是否获取Eureka服务器上的注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka服务器地址

