spring:
  application:
    name: adminV1
  profiles:
    active: local
server:
  port: 11003
  servlet:
    context-path: /business-admin/v1

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.panda.business.admin: debug
