server:
  port: 21002
spring:
  datasource:
    url: jdbc:mysql://198.19.249.159:3320/bamboo_system?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: root
    password: P@ssw0rd123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10 # 最大连接数
      connection-timeout: 30000 # 连接超时（毫秒）
      idle-timeout: 60000 # 空闲的连接的生命时长（毫秒）
      max-lifetime: 60000 # 连接的生命时长（毫秒）
      validation-timeout: 3000 # 验证连接有效性（毫秒）
