spring:
  application:
    name: document
  profiles:
    active: local
server:
  port: 11002
  servlet:
    context-path: /service-document

# 日志组件配置
logging:
  level:
    org.panda.service.doc: debug
