spring:
  application:
    name: microservice-doc
  profiles:
    active: local
  mvc:
    path-match:
      # SpringBoot2.6.X版本兼容自动化文档knife4J3.0
      matching-strategy: ant_path_matcher
server:
  port: 10002
  servlet:
    context-path: /doc-service

# 日志组件配置
logging:
  level:
    org.panda.service.doc: debug