# 服务相关配置
server:
  port: 10002
  servlet:
    context-path: /doc-service
spring:
  application:
    name: microservice-doc
  profiles:
    active: local
  mvc:
    path-match:
      matching-strategy: ant_path_matcher # SpringBoot2.6.X版本兼容knife4J3.0配置
