spring:
  application:
    name: document-service
  profiles:
    active: @profiles.active@
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  servlet:
    context-path: /document
