spring:
  application:
    name: business-helper-app
  profiles:
    active: @profiles.active@
server:
  port: 10003
  servlet:
    context-path: /biz-helper-app

mybatis:
  mapper-locations: classpath:mapper/*.xml
