spring:
  application:
    name: helper-app
  profiles:
    active: @profiles.active@
server:
  port: 10003
  servlet:
    context-path: /helper-app

mybatis:
  mapper-locations: classpath:mapper/*.xml
