spring:
  application:
    name: register-center

server:
  port: 12002

eureka:
  client:
    register-with-eureka: false # 用于指定该客户端实例是否在Eureka服务器上注册自己的信息以提供其他服务进行发现
    fetch-registry: false # 用于指定该客户端是否获取Eureka服务器上的注册信息
