spring:
  application:
    name: payment-service
  profiles:
    active: dev
  messages:
    basename: message/error/payment-error,message/info/payment-info
server:
  port: 11003

logging:
  level:
    org.panda.ms.payment: debug
