spring:
  application:
    name: payment
  profiles:
    active: local
  messages:
    basename: message/error/payment-error,message/info/payment-info
server:
  port: 11003
  servlet:
    context-path: /service-payment

logging:
  level:
    org.panda.ms.payment: debug
