spring:
  application:
    name: admin
  profiles:
    active: dev
server:
  port: 10002
  servlet:
      context-path: /biz-admin

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.panda.business.admin.v1: info
