spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 安全认证
security:
  user:
    name: admin
    password: 123456

# 分页插件mysql
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countsql