spring:
  application:
    name: payment
  profiles:
    active: local
  messages:
    basename: static/message/error/payment-error,static/message/info/payment-info
server:
  port: 11003
  servlet:
    context-path: /service-payment

logging:
  level:
    org.panda.service.doc: debug
