spring:
  application:
    name: business-admin
  profiles:
    active: local
  mvc:
    path-match:
      # SpringBoot2.6.X版本兼容自动化文档knife4J
      matching-strategy: ant_path_matcher
server:
  port: 11001
  servlet:
    context-path: /business-admin

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 分页插件mysql
page helper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=count-sql

logging:
  level:
    org.panda.business.admin: debug