spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/admin_system?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置初始化大小（默认0）、最小、最大（默认8）
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 测试连接
      validation-query: SELECT 1
      # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # 获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      # 归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      # 开启poolPreparedStatements后生效
      max-pool-prepared-statement-per-connection-size: 20

      # 配置扩展插件，常用的插件有stat:监控统计;wall:防御sql注入
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true                                                          #是否开启内置监控中的 Web-jdbc 关联监控的数据
        url-pattern: '/*'                                                      #匹配路径
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'              #排除路径
        session-stat-enable: true                                              #开启session监控功能
        session-stat-max-count: 1000                                           #session的最大个数,默认100
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true                                                          #是否开启内置监控页面，默认值为false
        url-pattern: '/druid/*'                                                #内置监控页面的访问地址
        reset-enable: false                                                    #是否启用重置按钮（禁用HTML中 Reset All按钮）
        login-username: admin                                                  #内置监控页面的登录页用户名
        login-password: 123456                                                 #内置监控页面的登录页密码
        allow: 127.0.0.1                                                       #IP白名单没有配置或者为空，则允许所有访问
        deny:                                                                  #IP黑名单若白名单也存在，则优先使用
      # Spring监控AOP切入点,配置多个英文逗号分隔
      aop-patterns: org.panda.business.admin.modules.*.service.repository
      # 对配置已开启的filters即stat(sql监控) wall（防火墙）
      filter:
        stat:                                                                  #配置StatFilter (SQL监控配置)
          enabled: true                                                        #开启SQL监控
          log-slow-sql: true                                                   #记录慢查询SQL
          slow-sql-millis: 1000                                                #慢查询，这里超过1s记录到日志
        wall:
          enabled: true
          config:
            update-allow: true                                                 #允许更新操作
            drop-table-allow: false                                            #禁止删表操作
            insert-allow:  true                                                #允许插入操作
            delete-allow: true                                                 #允许删除数据操作
            multi-statement-allow: true                                        #允许一次执行多条sql


# Actuator监控配置,开启监控所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 日志相关配置
logging:
  level:
    org.panda.business.admin: info
