spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bamboo_admin_v2?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
