server:
  port: 8888

spring:
  application:
    name: configservice
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
 classpath: config/
classpath: config/ordersevice


