spring:
  cloud:
    nacos:
      config:
        server-addr: bamboo-cloud-spt01.orb.local:8848
        namespace: 5314c8ad-67ba-420d-b499-6e5a5e93d432
        group: SPT_GROUP
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=false
      - optional:nacos:common-config.properties
