spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/official_system?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
