spring:
  application:
    name: notice
  profiles:
    active: local
  messages:
    basename: message/notice-message,message/notice-error
server:
  port: 11002
  servlet:
    context-path: /service-notice

logging:
  level:
    org.panda.service.doc: debug
